// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserControl.Data;

#nullable disable

namespace UserControl.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251024182109_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserControl.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<string>("ManagerEmail")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Users_Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Email");

                    b.HasIndex("ManagerEmail");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("UserControl.Models.User", b =>
                {
                    b.HasOne("UserControl.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerEmail")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Manager");
                });
#pragma warning restore 612, 618
        }
    }
}
